### ISSUE TITLE
"Text editor unit test integration" is not supported

### ISSUE THREAD

**Issue by lextm** [xunit/xamarinstudio.xunit#24]
Xamarin Studio 6 introduces the concept of "Enable text editor unit test integration" under Preferences | Text Editor | Source Analysis, which is not enabled by default.

It works for NUnit, but not yet for xUnit. Should investigate to see how the integration should be implemented.

**Comment by autonomy-rocks** [comment]
In order to get this to work you will most likely have to create your own implementation of https://github.com/mono/monodevelop/blob/master/main/src/addins/CSharpBinding/MonoDevelop.CSharp.UnitTests/CSharpNUnitSourceCodeLocationFinder.cs. I'm fairly certain the reason it currently doesn't work is because the implementation used currently is the NUnit implementation, which probably won't work with xUnit.

Also, you may notice that the nodes don't appear for [InlineData] attributes. They also don't appear for NUnit [TestCase] attributes like they're supposed to. This is a bug which I've reported.

https://bugzilla.xamarin.com/show_bug.cgi?id=41750

In your current code you set the `testCaseMethodAttributeMarker` in Manifest.addin.xml to `XUnit.TheoryAttribute`. The first thing I notice is that the namespace should be `Xunit` rather than `XUnit`. I also notice that in the NUnit addin, this is set to `NUnit.TestCaseAttribute` which more closely matches `Xunit.InlineDataAttribute`. So I have a feeling that it would be better to use `Xunit.InlineDataAttribute` for this.

**Comment by lextm** [comment]
Please read #77 for more details.
