### ISSUE TITLE
Follow NUnit add-in style to get rid of .NET remoting

### ISSUE THREAD

**Issue by lextm** [xunit/xamarinstudio.xunit#26]
There are issues related to .NET remoting, so we should attempt to get rid of it. The NUnit add-in again provides the basic building blocks. Just need to follow that example to develop two console runners (or a single one if the xUnit runner can support both v1 and v2).

**Comment by autonomy-rocks** [comment]
I've rewritten the project from scratch. So far I've managed to load tests using the new NUnit add-in style. All that's left is to write the Execute functionality in XUnitRunner. Perhaps you would be better at this than myself. I'm struggling a bit with it because I'm not familiar with xUnit's API. Odds are you're far more familiar with it than I am.

I'm not sure if you would want to use my project, because my naming conventions and coding style is a bit different than yours. But it should serve as a good starting point at least.

https://github.com/tstivers1990/xamarinstudio.xunit

**Comment by autonomy-rocks** [comment]
I've managed to get tests to populate and run. The only thing that's left to do now on the code I linked is fix reporting. It was working at one point, but it wasn't working correctly. Only the actual tests themselves and the first couple root nodes were showing the correct icons for the test results. The rest were stuck blank. Currently reporting is completely broken because of some unknown reason, and due to not having the slightest clue how the reporting actually works, because MonoDevelop.UnitTesting is completely undocumented, I'm struggling to figure it out.

**Comment by autonomy-rocks** [comment]
Also, you're more than welcome to copy my code if you wish. It currently has no licensing. I'm not attached to the code, and I'm more interested in getting a stable xUnit runner in MonoDevelop 6. So you can attach whatever license you like to the code and put it in this repository. Apologies in advance for the fact there is no attribution in the code I created and the license headers are all missing. I rewrote everything by hand using the NUnit addin, and used parts of the code here for reference on the xUnit parts.

**Comment by lextm** [comment]
@tstivers1990 The rule of thumb for open source, is that you should keep your copyright and choose a suitable license (MIT or any other, or even public domain). "So you can attach whatever license" is in fact not the way we commonly use.

I think you have got my idea by experimenting the things out, but as you discovered it is not an easy task to get it 100% correct. Instead of rushing to your code, I would do some experiments on my own with @z28wang to see if we can divide the task into small chunks. By moving step by step we might get a more stable result.

Thanks for sharing your kind assistance, and hope you don't feel disappointed at what I typed above. It is a project involving xUnit.net, Xamarin Studio/MonoDevelop, and Mono/.NET, so I rather not rush.

**Comment by lextm** [comment]
Below is the plan to "follow" the NUnit add-in style (but not to clone it),
- [x] Develop a console runner which can be tested separately.
- [x] Evaluate the protocol NUnit add-in uses to see if we can simplify that.
- [x] Implement the protocol between the console runner and xUnit add-in.
- [ ] Create unit test cases if possible.
- [ ] Create documentation on how we design and implement the protocol.

**Comment by x2bool** [comment]
By the way this whole thing shows how unreasonably complex XS's test runner is. When I did research on this, my conclusion was that actually only two framework-specific components were needed: 1) Test discovery - extracts meta information from a test project. 2) Test runner - actually runs tests. The fact that each framework needs to implement things such as test tree building and the things described above is definitely a red flag.

**Comment by lextm** [comment]
@x2bool if XamarinStudio can accept VS test adapters, then we don't even need to maintain this separate project. 

So will monitor actively Xamarin's plan on Xamarin Studio, and see how much we can reuse the existing bits. The above task list shows small steps that we can easily track while waiting for further news from Microsoft/Xamarin.

**Comment by lextm** [comment]
A very early prototype is now in #31. Will improve it and merge once it is ready.

**Comment by lextm** [comment]
Closed by #31.
