### ISSUE TITLE
Test aren't being discovered [VS for Mac]

### ISSUE THREAD

**Issue by zorthgo** [xunit/xamarinstudio.xunit#50]
Hi Guys, I am having an issue with xUnit and Visual Studio for Mac. None of my tests are being discovered.

These are the steps that I went through to test this issue:

1 - I created a test application on my Visual Studio on Windows.
2 - Ran my unit tests (they work fine)
3 - Commit the solution to git.
4 - Pull the solution to my Visual Studio for Mac
5 - Ran the tests (No go. They aren't being discovered).

I've also created the tests directly on my VS for mac. And still no go!..

Any help would be appreciated. Thanks! ;0)

Regards,

**Comment by lextm** [comment]
Visual Studio for Mac is not yet a supported environment of this addin. You have to wait.

**Comment by zorthgo** [comment]
Thanks for the reply!... So I am assuming that there are plans to support it?... :0)

**Comment by lextm** [comment]
Whether a plan is needed depends on how VS for Mac is going to evolve. If it decides to fully use VS for Windows unit testing infrastructure, then you should be able to directly use the VS xUnit.net runner instead of this addin.

Thus, I don't think any action will be executed in the coming weeks until Microsoft shares more insights on their side and a RC build of VS for Mac is published for testing.

**Comment by zorthgo** [comment]
Fair enough!... Thanks for the insight. ;0)

**Comment by lextm** [comment]
Just did some experiments. Microsoft/Xamarin do not yet provide a way to build/test/publish Visual Studio for Mac extensions. Hope it won't be a long wait though.

**Comment by zorthgo** [comment]
Thanks for looking further into it. I greatly appreciate it! 
Me as well, I hope it doesn't take too long. Until then, I can't really use VS for Mac for any serious programming.

**Comment by lextm** [comment]
@zorthgo Luckily with latest VS for Mac build and MonoDevelop.Addins package I can ship a test build,

https://github.com/xunit/xamarinstudio.xunit/releases/tag/v0.7.0

Please try it out and report back any issue you met.

**Comment by zorthgo** [comment]
Hi Lextm, thanks a lot!... I've been having issues with VS for Mac and couldn't test your extension until today. But after testing, I am still not able to run my unit tests. I installed:
- Your extension
- Xunit (2.2.0-beta5-build3474)
- Xunit Console Runner (this is because the Visual Studio runner wouldn't install)

But when I rebuild, none of the tests show up. Do I need to install anything else?

By the way my VS for Mac version is Preview 3 (7.0 Build 1077). 

Thanks for your time! ;0)

**Comment by lextm** [comment]
Can you test using xUnit.NET 2.1.0 assemblies? I have no plan yet for 2.2.0 as that's still beta bits.

**Comment by zorthgo** [comment]
Ok, I tried testing with xUnit 2.1.0 but the xunit.assert package doesn't seem to be compatible with .net core. I keep getting the error message below when I try to add the xunit nugget package. 

>Package xunit.assert 2.1.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package xunit.assert 2.1.0 supports:
>  - dotnet (.NETPlatform,Version=v5.0)
>  - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)

**Comment by lextm** [comment]
Aha, I see. I will try to update the VS for Mac add-in version to 2.2.0 beta and then make a new download available. Then you can test if it works.

**Comment by zorthgo** [comment]
Sounds great. Thanks! ;)

**Comment by lextm** [comment]
You can download 0.7.1 and let me know if it works,

https://github.com/xunit/xamarinstudio.xunit/releases/tag/v0.7.1

**Comment by Javier-Rotelli** [comment]
Hi! 
I'm trying to use this extension, but it's not working.
it shows this message when i try to install it
![image](https://cloud.githubusercontent.com/assets/5343874/24117926/c49e9c8e-0d8a-11e7-8815-e137d28b4935.png)

**Comment by lextm** [comment]
@Javier-Rotelli are you sure you are installing the right extension? The text clearly points to another add-in.

**Comment by Javier-Rotelli** [comment]
@lextm not 100% sure. 
in the entension manager it says: "xUnit.NET 2 testing framework support", also, it's the only one that shows up when i search for "xunit" in the gallery. 

maybe the error is coming from a dependency?

**Comment by Javier-Rotelli** [comment]
@lextm nevermind, that error seems to be unrelated, disabling the ios develop extension and restarting visual studio got it working. if you want i'll delete my replies as those only polute this thread.

Cheers!

**Comment by patrycjapico** [comment]
Hi guys
I end up in that topic looking for a solution for my problem which was quite similar but might not be the same. I found out what the cause was and wanted to share in case someone has the same issue.

So I could not restore xunit.assert package on my Mac in Visual Studio Community for Mac version 7.1.3 (build 1) in any of my test projects. I tried to do that manually, the message was that "The package was restored with warnings" and the warning was that there is not assert package - still no success. When trying to remove it I got notified that the path to the package was empty.
And then I remembered that once I experienced nuget packager issues on Windows where I did not quite know what was going on. And the reason there was the nuget cache got corrupted.
So I tried the same route here and removed all packages stored in nuget cache on Mac (it is located in Users/<user name>/.nuget), purged my repository, and tried to reload the solution again. All packages were restored successfully and the problem was gone!

So in case someone encounters the same thing - this is how to fix that.
