### ISSUE TITLE
The remote xunit runner does not work as expected

### ISSUE THREAD

**Issue by lextm** [xunit/xamarinstudio.xunit#61]
This is a follow-up item for #60 .

The runner returns empty results for test cases so that no test case can be discovered. Some debugging is required.

**Comment by lextm** [comment]
Fixed in 0.7.4.

**Comment by guardrex** [comment]
Hello @lextm! I was wondering how the release for these fixes (here and #60) work given the versions in the wild ... Do these changes take effect on the next stable release of xunit, which would be v2.3.0 (when that ships)?

Also, I don't understand your comment over on #60 ...

> xUnit.net based .NET Core testing can run properly without this extension. So I think probably it is time for Xamarin/Microsoft to take over the responsibility.

Wondering how that relates to the xUnit running from within the VS for Mac IDE with these #60 and #61 fixes? ... Are Xam/MS supposed to do something on their end now to make it work?

**Comment by lextm** [comment]
So to be clearer.

* If your project type is .NET Core based, then xUnit.net support is provided by .NET Core infrastructure, and Visual Studio for Mac by default. You can run test cases without even installing this extension.
* If your project type is .NET Framework/Mono based, then this extension provides you the ability to run/debug xUnit.net test cases.

Currently this extension is only tested against xUnit.net 2.2.x stable release. 2.3.x release introduces many changes, which won't be supported soon.

**Comment by guardrex** [comment]
@lextm Thanks for explaining. I couldn't get it to work again (same result as I show in #60) with the release version of VS for Mac with the 15.0.0 version of MSTest and the 2.2.0 version of xUnit running a `netcoreapp1.1` project. Actually, it's the exact project I have in the [.NET Core tutorial](https://docs.microsoft.com/en-us/dotnet/core/tutorials/using-on-mac-vs-full-solution). It's Step 8 that I'm waiting to get updated for running tests via the IDE.

The tests still run fine from the command line, so this seems to be an issue on the VS for Mac infrastructure side. Should I open an issue using the **Report a Problem** feature from the Welcome Screen in VS for Mac?

**Comment by lextm** [comment]
@GuardRex You can uninstall this extension (and restart VS for Mac) and test again, before reporting to Microsoft. I think it is something Microsoft/Xamarin should take care of, instead of me.

**Comment by lextm** [comment]
@GuardRex can you test with the attached test solution? It works fine on my machine with VS for Mac, and no xamarinstudio.xunit installed.

[dotnetcore.zip](https://github.com/xunit/xamarinstudio.xunit/files/1075366/dotnetcore.zip)

**Comment by guardrex** [comment]
I'm good ... the sample for the doc is working fine now from the IDE. The only unresolved issue is the VSMac UI label content describing the tests, and it turns out that they knew about it a few weeks ago: https://bugzilla.xamarin.com/show_bug.cgi?id=56921

Thanks again :beers: for your help!

I know you said on the docs issue that given we're showing a Core app it makes sense to not worry about the extension. If you think that the extension must/should be covered there ... saying something to the effect that for netfx projects that are built with VSMac *you need this extension and here's where to get it* ... let me know, and I'll open a new issue over there and ping you on that so we can get the language right. As it stands, the doc says nothing at all about the extension, and that might be a bad *BAD* thing for it not to at least mention it.
