### ISSUE TITLE
Unable to get xunit tests in Unit Tests toolwindow

### ISSUE THREAD

**Issue by parthopdas** [xunit/xamarinstudio.xunit#67]
I am using VS4Mac v7.0.1 (build 24).
I tried with both the v0.7.5 (from gallery) and v0.7.6 from releases.

With the latter configuration i get the tests listed but I cannot run them. With the former, the tests arent listed.

I have tried with both xunit 2.2.0 and 2.1.0.

Any ideas I can try next? Or how I can get additional diagnostic information?

**Comment by parthopdas** [comment]
Also is there a reason why this adding is coupled to a particular version of xUnit? 

The xunit adapter for Visual Studio for Windows works with any xunit version. And it seems, the nunit addin for vs4mac works with any version of nunit as well.

**Comment by lextm** [comment]
It is much easier to support only one version of xUnit.net, so we used to only support 2.1.0 before 2.2.0 is released. So now with 2.2.0 released, the support version changes to 2.2.0.

Note that this means if you meet any issue with xUnit.net 2.2.0 the current maintainer of this repo would officially take a look at it. This extension might still work for 2.1.0 or 2.0.0, but due to limited resource the repo maintainer would not be able to verify or troubleshoot for you.
